# Generated by Django 5.2.7 on 2025-10-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_driver_route_alter_truckingaccount_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckingaccount',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver'),
        ),
        migrations.AlterField(
            model_name='truckingaccount',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.route'),
        ),
    ]


